### PR TITLE
Fix Rectange snap on Draw

### PR DESCRIPTION
**Pull request by ianjanicki**
When drawing a Rectangle, and the user wants to snap to a nearby vertex, this fix makes sure it lands on the vertex vs. the current x,y of the cursor.

### CODE REVIEW

**Comment by codeofsumit** [comment]
Thanks for the PR 🎉 . Does this still work on mobile for snapping? Can you verify this?

**Comment by codeofsumit** [comment]
@ianjanicki thanks for checking. Could you also test it on a real mobile device? Because on mobile there are other events used inside leaflet and it affects the behaviour of this lib

**Comment by ianjanicki** [comment]
@codeofsumit Would love to! But have a few questions about doing that:
1. Your `CONTRIBUTING.md` is a little confusing/misleading. `/index.html` does not work for me; it's a blank page. Are you referencing `/demo/index.html`? This works on my machine.
2. I was trying to use Node's `http-server` to host `demo/index.html` so I could test it on my phone (using an Android phone + Mac) — but the `addControls` method fails, so there's no Leaflet.pm toolbar, so that was a dead-end.
3. I noticed you host on now.sh, and I'm curious if you host for every branch — if this PR has a build URL would gladly test it there.

Let me know if I'm doing anything wrong here.

**Comment by codeofsumit** [comment]
Sorry @ianjanicki, accidentally fixes this already through #448.
But I took your feedback and made changed to the contributing.md and hope it makes things clearer where and how to manually test your changes on a working map 👍
Please open another issue in case contribution is still hard/confusing. Thank you for your time and work!

**Pull request closed without merging**
