### PR TITLE
Fixed  Multi-node (6000+) polygon editing performance issue

### PR DESCRIPTION
**Pull request by lobovmaxim**
I have fixed the problem (Multi-node (6000+) polygon editing performance). The decision is show only N count of markers near cursor (optionaly). I am not sure on my edit in findDeepMarkerIndex (L.PM.Edit.Line.js), maybe it will be incorrect work in some cases and I haven`t time to think deeper.

### CODE REVIEW

**Comment by hefler** [comment]
I've been testing this proposed solution and so far I'm having problems when setting `enableGlobalEditMode` programatically. I haven't have the time to look into it but wanted to give a heads up.

**Comment by codeofsumit** [comment]
@lobovmaxim thanks so much for your work on this. I'm about to fix this myself with a different technique but the same outcome. Can you please send me a polygon so I can stress test my implementation? [Send it via email: sumit@geoman.io](mailto:sumit@geoman.io)


Thanks in advance

**Comment by lobovmaxim** [comment]
@codeofsumit I have send the polygon json by email

**Comment by codeofsumit** [comment]
Alright, @lobovmaxim thanks a lot for the JSON. I will close this PR now - let's continue the conversation in #366. Sneak Peak:

perf

**Comment by codeofsumit** [comment]
It's done!
https://github.com/geoman-io/leaflet-geoman/issues/366#issuecomment-601660278

**Pull request closed without merging**
