### PR TITLE
Added curve drawing/editing support

### PR DESCRIPTION
**Pull request by qpincon**
As discussed in #872.

If the [Leaflet.curve](https://github.com/elfalem/Leaflet.curve) plugin is defined, the drawing of curve is enabled (with editing, dragging, rotation). 
Touch support is also handled, however not tested extensively.

Limitations:
At the moment there is not self-intersection detection for curves, and cutting the shape with the cut tool is not possible. It is a possible improvement in the future.

Let me know if you have any question.

### CODE REVIEW

**Comment by Falke-Design** [comment]
Thanks for this nice feature! I have spoken with @codeofsumit and we decided that it makes sense to add this as a plugin, because it increases the package size over 100kb and we want that `Leaflet.curve` is added in the dependencies of package.json (so that it is working without that the user needs to include external Javascript)

If it is ok for you, we will setup a project `leaflet-geoman-curve` in the `geoman-io` organisation and then you can create a PR for the new repo.

**Comment by qpincon** [comment]
Sure, no problem with that!

**Comment by Falke-Design** [comment]
@qpincon new repo is created, can you please create a PR there: https://github.com/geoman-io/leaflet-geoman-curve

**Comment by qpincon** [comment]
Thank you! 
I had to do some special case implementation for the handling of the rotation/dragging in the source code of those functions however. Should I Leave them here, or should I find a way to integrate them into the plugin you think?

**Comment by Falke-Design** [comment]
Can we do it in following steps:
1. Make it possible to draw / edit
2. Make it possible to drag, rotate, ...

And I want to look where we need to implement API interfaces for plugins. So let us start with draw and edit ok?

**Comment by AndrejGajdos** [comment]
@Falke-Design I tried the demo in development branch in https://github.com/geoman-io/leaflet-geoman-curve but it doesn't work.

**Comment by Falke-Design** [comment]
@AndrejGajdos we currently stopped and never finished the development of leaflet-geoman-curve

**Pull request closed without merging**
