### PR TITLE
Add typescript typings

### PR DESCRIPTION
**Pull request by ryan-morris**

### CODE REVIEW

**Comment by ryan-morris** [comment]
`npm ci` reported the `package-lock.json` file being out of date so I needed to do an `npm install`. This did touch a few of the dependencies so hopefully everything looks ok.

**Comment by codeofsumit** [comment]
@ryan-morris we are not typescript users - can you please explain what's happening? What are the changes to the webpack configs do? How does the output differ?

Any additional info about what this PR does is appreciated - happy to merge once we understand it.

Cheers

**Comment by ryan-morris** [comment]
@codeofsumit I had put some information on #659 . But I'll try to elaborate some:

The `leaflet-geoman.d.ts` file is what supplies the typescript compiler with information about what leaflet-geoman does and has available. The one in this PR does not cover everything but it has covered all of my use cases so far. This file must be included in the distributed npm package so the end user's compiler has access to it. The typscript compiler looks at the package.json for the "types" property that points to this file.

For the webpack changes, I have not really had to mess with webpack directly before so there may be a better way. Like I mentioned above the `leaflet-geoman.d.ts` just needs to be included in what gets published to npm. The best way I saw to get this file into the dist output was to use that plugin, since `leaflet-geoman.d.ts` isn't involved at all in the current compilation pipeline. It should just be copying `leaflet-geoman.d.ts` to dist and nothing else. If there is a simpler way that I overlooked just let me know and I'll get that changed.

**Comment by codeofsumit** [comment]
Sounds reasonable. Have you tried this locally by installing the cloned repo / your branch into your other project via `npm install <path/to/local/lib>`? And the typescript file was included?

**Comment by ryan-morris** [comment]
Yes, doing an npm install to the local folder where the cloned copy of this PR is, I get `node_modules/@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.d.ts`. I do have to run `npm run build` inside the cloned copy first, otherwise no dist is included at all but that's to be expected.

**Comment by codeofsumit** [comment]
arrrgh merged it into `master` instead of `develop`

**Comment by ryan-morris** [comment]
@codeofsumit apologies, I didn't realize you wanted PRs to target that branch. If you want to revert, I can redo changes against develop and open a new PR targeting that branch, just let me know.

**Comment by hoetmaaiers** [comment]
Is any follow up work being done on the typing? I am willing to update the typing while implementing, but maybe other people are also working on this so we can spread the work?

**Comment by Falke-Design** [comment]
Hey @hoetmaaiers it would be very nice if you do this.
I think there are no other peoples are working on this, maybe @lukekroon but I heard nothing anymore from him. https://github.com/geoman-io/leaflet-geoman/issues/744#issuecomment-754611483

**Comment by ryan-morris** [comment]
@hoetmaaiers I have added typings to the root of the project. It looks like there are some issues, see #744

**Comment by hoetmaaiers** [comment]
@ryan-morris Indeed I found those types, but though they are a good start, I think they don't cover a big part of the API? Are any plans made to further extend these types? 

I have a feeling, the documentation is also slightly waiting for an upgrade on this?

**Comment by codeofsumit** [comment]
@hoetmaaiers @ryan-morris just wanted to chime in here: 
@Falke-Design and I are the main maintainers of this library (he more than me by now) but none of us ever used typescript. So typescript support won't come from us and we can't check contributions properly here.
We rely on community contributions like yours and we will merge them when peer-reviewed by other typescript-savvy community members / contributors in the hopes of increased support for typescript users. So anything that you guys & girls can contribute is greatly appreciated.

**Comment by hoetmaaiers** [comment]
It is perfectly reasonable Typescript typings are improved by community contributions and I'm surely willing to help on this.

Can I assume the documentation in `README.md` is considered complete? I get the feeling (might be wrong) not every api  detail is resembled over there which makes me search numerous Stackoverflow threads for something that in my idea should be documented?

I am asking because Typescript typings also provide documentation, so in orde to write them clear documentation is a necessity?

**Comment by codeofsumit** [comment]
> Can I assume the documentation in `README.md` is considered complete? 

From anything considered a "public api" I think yes, the README is pretty complete. At least I'm not aware of anything we built to be used but did not document. @Falke-Design what do you think?

**Comment by Falke-Design** [comment]
@hoetmaaiers yes the documentation should be complete, I refactored and updated it for the latest release 2.9.0.

**Comment by hoetmaaiers** [comment]
I am currently updating my `@ts-ignore` parts to typings. I'll contribute these to the library once done. When I am unsure of the documentation I'll ask here ;)

**Comment by Falke-Design** [comment]
@hoetmaaiers let us write here #790

**Pull request merged**
