### PR TITLE
Feature: Rotation

### PR DESCRIPTION
**Pull request by Falke-Design**
Implemented rotation for Polyline, Polygon and Rectangle

- Global rotation mode
- Layer rotation mode
- layer can be rotated by angle `.rotateLayer(angle)`
- layer can be rotated to angle `.rotateLayerToAngle(angle)`
- working with marker limits
- Drawing a rectangle with rotation. Thx to @dihilton for the nice code #386

Feature Requests: #273, #354, 

Rotation calculation comes from: https://github.com/w8r/Leaflet.Path.Transform ❤

rotation
rotate_big

Rotation Angle:
degree_circle

### CODE REVIEW

**Comment by piotrek-b** [comment]
Hi, so I've installed your changes as a dep to my project but I'm getting
```
this._layer.getLatLngs is not a function
```
When trying to use resizing, doesn't matter if there are any layers drawn or not. Aren't you encountering the same?

**Comment by Falke-Design** [comment]
@piotrek-b have you used the correct branch? `rotationV2`? Resizing is not a part of this PR

**Comment by piotrek-b** [comment]
Yes, I'm using this one. I do want to use rotation so I've picked this one up, it's just that resizing is not working for me anymore after installing

**Comment by Falke-Design** [comment]
Which resizing do you mean? From the rectangle?

**Comment by piotrek-b** [comment]
Any in fact, I'm getting this error after clicking on vertex edit control

**Comment by Falke-Design** [comment]
Is working for me ... When I build the the script this comes out and it works: (remove .txt)
[leaflet-geoman.min.js.txt](https://github.com/geoman-io/leaflet-geoman/files/6005903/leaflet-geoman.min.js.txt)

**Comment by piotrek-b** [comment]
Ok I know the reason, it does not seem to be working when image overlay is being used, as it does not implement `getLatLngs`

**Comment by Falke-Design** [comment]
Ah yeah 👍 I will fix this tomorrow thanks

**Comment by piotrek-b** [comment]
Great, appreciate the effort!

**Comment by piotrek-b** [comment]
@Falke-Design any luck with this one ? 🙂

**Comment by Falke-Design** [comment]
@piotrek-b I fixed it, can you please test

**Comment by piotrek-b** [comment]
It's working fine now, thanks!

**Comment by Falke-Design** [comment]
@codeofsumit Readme is added [demo](https://github.com/Falke-Design/leaflet.pm/tree/rotationV2) and icon is sized down

**Comment by AndrejGajdos** [comment]
Awesome, I was waiting for this feature.

**Review by codeofsumit — APPROVED** [review]
Tested locally and it worked like a charm.
Fantastic work 👏 👏

**Comment by Khoroshavin** [comment]
how i can switch off this function from my map?

**Comment by Falke-Design** [comment]
@Khoroshavin 
Same like other buttons:
```
map.pm.addControls({
    rotateMode: false
});
```

**Comment by Keuta** [comment]
Hi there, I have got an issue with "rotation" and "drag layer".
I create a rectangle from my code as follow : `new_planche = L.rectangle([SW,NE], {pmIgnore: false}).addTo(map{{parcel.pk}});`
I can rotate then move my layer with the pm controls, but if i move then rotate the layer, I've got this error : 
image
Am I doing something wrong ?

**Pull request merged**
