### PR TITLE
Drag events for Marker

### PR DESCRIPTION
**Pull request by Falke-Design**
Adding drag events to marker and circle while edit mode.

Also fixed that CircleMarker fired "pm:edit" twice:
1. Dragging.js -> _dragMixinOnMouseUp -> _fireEdit 
2. _dragMixinOnMouseUp -> "pm:dragend" -> _onMarkerDragEnd -> _fireEdit

Fixed Issue #512

### CODE REVIEW

**Comment by StripedBanana** [comment]
I do confirm that regular leaflet events work on simple L.marker objects. Although it seems kind of weird to me that features coming from the geoman sidebar would not be treated the same way regarding events : when I'm creating a marker, I would use regular leaflet events, but when I'm creating anything else I must use geoman `pm:*` events.

So I think it's not really a functionality issue, but more like a conception choice. Thank you for your work on this plugin by the way guys, it's really great 👍

**Comment by Falke-Design** [comment]
Yes @StripedBanana is right. It has only the effect that all layers can use the same event. And the User don't need to think of if it is a Marker or not.

With that it is easier to do following:
```
map.on('pm:create',(e)=>{
  e.layer.on('pm:drag',logEvent)
});
```

instead of:
```
map.on('pm:create',(e)=>{
  if(e.layer instanceof L.Marker){
    e.layer.on('drag',logEvent)
  }else{
    e.layer.on('pm:drag',logEvent)
  }
});
```

**Comment by StripedBanana** [comment]
Actually I was partially wrong. Look at this fiddle I made : https://jsfiddle.net/7r4sfnu5/

When you enable the Geoman's dragging mode, the `dragstart` does not get called anymore on the `L.Marker` (`dragend` still does for some reason). This is problematic to me, as I have no way to use `dragstart` callbacks on my `L.Marker`s when I'm in Geoman's dragging mode.

**Comment by codeofsumit** [comment]
You are right - I now understand the need for this 👍 .

**Comment by Falke-Design** [comment]
@StripedBanana "your" problem was because of the line `this._layer.off('dragstart', this._onPinnedMarkerDragStart, this);` in the `disable` Marker function. This is a pro feature and referenced to it, but it doesn't exists.

I removed it and now it works well.

**Comment by Falke-Design** [comment]
@codeofsumit About what tests you are thinking of? Until now, there are nowhere `drag` events tested. If it should be have tests, I need the PR #592 merged. It adds support for drag in cypress tests.
Readme doesn't need to be updated, because it is already described. There are no excludes for markers.
Merge conflicts are resolved.

**Pull request merged**
