### PR TITLE
Added danish translations

### PR DESCRIPTION
**Pull request by eaxexe**
Added danish translations :)

### CODE REVIEW

**Comment by Falke-Design** [comment]
@eaxexe can please resolve the conflict

**Comment by eaxexe** [comment]
> @eaxexe can please resolve the conflict

Should be resolved :smile:

**Comment by Falke-Design** [comment]
Maybe you can also pull the latest develop version, where the tests not failing

**Comment by eaxexe** [comment]
> Maybe you can also pull the latest develop version, where the tests not failing

This means I have to create a new pull request, right? I can't find a way of updating this one.

**Comment by Falke-Design** [comment]
when you have the git terminal, you can call `git pull https://github.com/geoman-io/leaflet-geoman.git develop`

**Comment by eaxexe** [comment]
Replaced with #670

**Pull request closed without merging**
