### PR TITLE
Update typescript interface

### PR DESCRIPTION
**Pull request by ocram1095**
While using it in typescript i found some missing functions in interface.

### CODE REVIEW

**Comment by ryan-morris** [comment]
@ocram1095 , instead of using `any` can you change it to map to the actual options. It looks like `MapDrawOptions` is what should be passed in there.

**Review by codeofsumit — CHANGES_REQUESTED** [review]
Awesome thanks a lot for your work on this. Please also fix the merge conflicts in addition to the already suggested changes 👍

**Comment by Falke-Design** [comment]
@ryan-morris is this PR covered with the new release? Can we close it or should it be merged?

**Comment by ryan-morris** [comment]
@Falke-Design not all these changes were included in the last release. If @ocram1095 doesn't get a chance to fix the conflicts I'll include the changes in the next set of changes I've been working on.

**Pull request closed without merging**
